# Generated by Django 4.0.3 on 2022-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.CharField(max_length=100, null=True)),
                ('ten_sach', models.CharField(max_length=100, null=True)),
                ('ngay_nhap', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('nguoi_nhap', models.CharField(max_length=100, null=True)),
                ('so_luong', models.IntegerField(null=True)),
                ('the_loai', models.CharField(max_length=100, null=True)),
                ('tac_gia', models.CharField(max_length=100, null=True)),
                ('don_gia', models.FloatField(null=True)),
                ('gia_ban', models.FloatField(null=True)),
                ('nha_xuat_ban', models.CharField(max_length=100, null=True)),
                ('nam_xuat_ban', models.IntegerField(null=True)),
            ],
        ),
    ]
