# Generated by Django 4.0.3 on 2022-05-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='nam_xuat_ban',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sach',
            name='so_luong',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id_HD', models.CharField(default='HD_', max_length=100, primary_key=True, serialize=False, verbose_name='Mã hóa đơn')),
                ('ngay_lap_HD', models.DateTimeField(auto_now_add=True, null=True)),
                ('tong_tien', models.FloatField(null=True)),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('Thẻ ngân hàng', 'Thẻ ngân hàng'), ('Tiền mặt', 'Tiền mặt')], max_length=100, verbose_name='Phương thức thanh toán')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='khach_hang', to='book.person', verbose_name='Khách hàng')),
                ('nguoi_lap_HD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhan_vien', to='book.person', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name_plural': 'Hóa đơn',
            },
        ),
    ]
