# Generated by Django 4.0.3 on 2022-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_sach_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100, null=True)),
                ('ngay_sinh', models.DateField(auto_now_add=True, null=True)),
                ('so_dien_thoai', models.CharField(max_length=13, null=True)),
                ('dia_chi', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('chuc_vu', models.CharField(choices=[('nhân viên', 'nhân viên'), ('thủ kho', 'thủ kho'), ('chủ nhà sách', 'chủ nhà sách')], max_length=100, null=True)),
            ],
        ),
    ]
