# Generated by Django 4.0.3 on 2022-05-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_sach_nam_xuat_ban_alter_sach_so_luong_hoadon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='ngay_lap_HD',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ngay_sinh',
            field=models.DateField(null=True, verbose_name='Ngày sinh'),
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(null=True)),
                ('gia_ban', models.FloatField(null=True)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.hoadon', verbose_name='Hóa đơn')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.person', verbose_name='Khách hàng')),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.sach', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết hóa đơn',
                'unique_together': {('hoa_don', 'khach_hang')},
            },
        ),
    ]
