# Generated by Django 4.0.3 on 2022-05-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_nhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='nguoi_nhap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.nhanvien'),
        ),
    ]
