# Generated by Django 4.0.3 on 2022-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_hoadon_ngay_lap_hd_alter_person_ngay_sinh_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chitiethoadon',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chitiethoadon',
            name='gia_ban',
        ),
        migrations.RemoveField(
            model_name='chitiethoadon',
            name='khach_hang',
        ),
    ]
