# Generated by Django 4.0.3 on 2022-05-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_sach_nguoi_nhap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='ngay_nhap',
            field=models.DateField(null=True),
        ),
    ]
