# Generated by Django 4.0.3 on 2022-05-24 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_alter_sach_ngay_nhap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.CharField(choices=[('nhân viên', 'nhân viên'), ('thủ kho', 'thủ kho'), ('chủ nhà sách', 'chủ nhà sách')], max_length=100, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='dia_chi',
            field=models.CharField(max_length=1000, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(max_length=100, null=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ngay_sinh',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='so_dien_thoai',
            field=models.CharField(max_length=13, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, null=True, verbose_name='Họ tên')),
                ('so_dien_thoai', models.CharField(max_length=13, null=True, verbose_name='Số điện thoại')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email')),
                ('dia_chi', models.CharField(max_length=1000, null=True, verbose_name='Địa chỉ')),
                ('ngay_lap_tk', models.DateTimeField(null=True)),
                ('than_thiet', models.BinaryField(default=0)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='Mật khẩu')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id_HD', models.CharField(default='HD_49868', max_length=100, primary_key=True, serialize=False)),
                ('ngay_lap_HD', models.DateTimeField(null=True)),
                ('tong_tien', models.FloatField(null=True)),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('Thẻ ngân hàng', 'Thẻ ngân hàng'), ('Tiền mặt', 'Tiền mặt')], max_length=100, verbose_name='Phương thức thanh toán')),
                ('id_KH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.khachhang')),
                ('nguoi_lap_HD', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book.nhanvien')),
            ],
        ),
    ]
