# Generated by Django 4.0.3 on 2022-05-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_nhanvien_chuc_vu_alter_nhanvien_dia_chi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='dia_chi',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='user',
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='id_HD',
            field=models.CharField(default='HD_92437', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ngay_lap_tk',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='than_thiet',
            field=models.BinaryField(blank=True, default=0),
        ),
    ]
