# Generated by Django 4.0.3 on 2022-05-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_hoadon_id_hd_alter_khachhang_than_thiet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='than_thiet',
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='id_HD',
            field=models.CharField(default='HD_39945', max_length=100, primary_key=True, serialize=False),
        ),
    ]
