# Generated by Django 4.0.3 on 2022-05-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_hoadon_id_hd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='nguoi_lap_HD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.nhanvien'),
        ),
    ]
