# Generated by Django 4.0.4 on 2022-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_hoadon_da_tra_alter_hoadon_tong_tien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(default='profile1.png', null=True, upload_to=''),
        ),
    ]
