# Generated by Django 4.0.4 on 2022-06-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_chitiethoadon_sach_and_more'),
        ('book', '0015_alter_person_profile_pic'),
    ]

    operations = [
    ]
