# Generated by Django 4.0.3 on 2022-06-09 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_sach_ngay_nhap'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhapSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sach', models.CharField(max_length=100, null=True, verbose_name='Tên sách')),
                ('ngay_nhap', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Ngày nhập')),
                ('so_luong', models.PositiveIntegerField(null=True, verbose_name='Số lượng')),
            ],
        ),
    ]
