# Generated by Django 4.0.3 on 2022-06-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_nhapsach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhapsach',
            options={'verbose_name_plural': 'Nhập sách'},
        ),
    ]
