# Generated by Django 4.0.3 on 2022-06-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_merge_20220610_1505'),
        ('book', '0019_inventory'),
    ]

    operations = [
    ]
